# Generated by Django 3.2.2 on 2021-05-09 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sluge',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='DEFAULT VALUE', max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='stats',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
